# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc2777daa7a90a21504369a2a87d28476aa02fdfaecd75d11b40f9e2b0cffc032f7952437766034f98babf7ac8012e8d428b2cd88ea66bc48a0f0587ddb3867c

test:
  secret_key_base: e7f2d214624863371931662d17ecfd309b827f48fe1e0ae43d105625677caef0663479f60613ca2b5e05f34f7d55ac08ad797fcf72c933c9173e4e9385f61abc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
